export default {
  async fetch(request) {
    const url = new URL(request.url);
    const path = url.pathname === '/' ? '/index.html' : url.pathname;

    if (path === '/index.html') return htmlResponse(indexHTML);
    if (path === '/cafes.html') return htmlResponse(cafesHTML);
    if (path === '/cafe.html') return htmlResponse(cafeHTML);
    if (path === '/booking.html') return htmlResponse(bookingHTML);
    
    return htmlResponse(indexHTML);
  }
};

function htmlResponse(html) {
  return new Response(html, {
    headers: { 
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=3600"
    }
  });
}

// ページ1: メインページ
const indexHTML = `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>yurucafe</title><link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;500&family=Zen+Old+Mincho:wght@400;600&display=swap" rel="stylesheet"><style>:root{--bg:#F9F5F0;--text:#4A3B32;--accent:#A67B5B;--light:#E8Ddd4;--white:#fff;}*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'Zen Kaku Gothic New',sans-serif;background:var(--bg);color:var(--text);line-height:1.8;}h1,h2,h3{font-family:'Zen Old Mincho',serif;font-weight:600;}a{text-decoration:none;color:inherit;transition:.3s;}.container{max-width:800px;margin:0 auto;padding:0 20px;}header{padding:20px 0;border-bottom:1px solid var(--light);}.nav-inner{display:flex;justify-content:space-between;align-items:center;}.logo{font-family:'Zen Old Mincho',serif;font-size:1.5rem;letter-spacing:.05em;}.hero{height:80vh;display:flex;align-items:center;justify-content:center;text-align:center;background:linear-gradient(rgba(74,59,50,.3),rgba(74,59,50,.3)),url('https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=800');background-size:cover;color:var(--white);margin-bottom:40px;}.hero-title{font-size:2rem;margin-bottom:20px;line-height:1.4;text-shadow:0 2px 4px rgba(0,0,0,.3);}.section-title{text-align:center;font-size:1.5rem;margin-bottom:30px;position:relative;}.section-title::after{content:"";display:block;width:40px;height:1px;background:var(--accent);margin:15px auto 0;}.btn{display:inline-block;background:var(--accent);color:var(--white);padding:12px 30px;border-radius:4px;font-size:1rem;margin-top:20px;}.btn:hover{background:var(--text);}footer{text-align:center;padding:40px 0;font-size:.8rem;border-top:1px solid var(--light);}</style></head><body><header><div class="container nav-inner"><a href="/" class="logo">yurucafe</a><nav><a href="/cafes.html" style="font-size:.9rem;">カフェを探す</a></nav></div></header><div class="hero"><div class="container"><h1 class="hero-title">一杯のコーヒーが、<br>心の国境を溶かす。</h1><p style="font-size:1rem;opacity:.9;">留学生と地域をつなぐ、ゆるやかな対話の場</p></div></div><section class="container"><h2 class="section-title">Concept</h2><div style="text-align:center;max-width:600px;margin:0 auto;"><p>異国の地で学ぶということ。<br>それは、新しい発見の連続であると同時に、<br>言葉にできない孤独を抱えることでもあります。</p><p>yurucafeは、そんな日常に「余白」をつくるプロジェクトです。<br>ここは、完璧な言語を話す必要がない場所。</p><p>コーヒーの香りに包まれながら、<br>あなたの故郷の話、私の日常の話をしませんか？</p></div></section><section class="container" style="text-align:center;"><h2 class="section-title">Join Us</h2><p>静かな対話と、深い味わいのコーヒーを用意して<br>あなたを待っているカフェがあります。</p><a href="/cafes.html" class="btn">提携カフェを見る</a></section><footer><p>&copy; 2024 yurucafe Project.<br>Designed for connection, not for profit.</p></footer></body></html>`;

// ページ2: カフェ一覧（短縮版）
const cafesHTML = `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>カフェ一覧 | yurucafe</title><link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;500&family=Zen+Old+Mincho:wght@400;600&display=swap" rel="stylesheet"><style>:root{--bg:#F9F5F0;--text:#4A3B32;--accent:#A67B5B;--light:#E8Ddd4;--white:#fff;}*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'Zen Kaku Gothic New',sans-serif;background:var(--bg);color:var(--text);line-height:1.8;}.container{max-width:800px;margin:0 auto;padding:0 20px;}header{padding:20px 0;border-bottom:1px solid var(--light);}.nav-inner{display:flex;justify-content:space-between;align-items:center;}.logo{font-size:1.5rem;font-family:'Zen Old Mincho',serif;}.cafe-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:30px;margin:60px 0;}.cafe-card{background:var(--white);border:1px solid var(--light);border-radius:8px;overflow:hidden;box-shadow:0 4px 6px rgba(0,0,0,.02);transition:transform .2s;}.cafe-card:hover{transform:translateY(-5px);}.card-img{height:200px;background:#eee;display:flex;align-items:center;justify-content:center;color:#999;}.card-content{padding:20px;}.cafe-name{font-size:1.25rem;margin-bottom:10px;}.btn{display:inline-block;background:var(--accent);color:var(--white);padding:12px 30px;border-radius:4px;margin-top:20px;}</style></head><body><header><div class="container nav-inner"><a href="/" class="logo">yurucafe</a><nav><a href="/" style="font-size:.9rem;">トップへ</a></nav></div></header><div class="container"><h2 style="text-align:center;margin:40px 0 20px 0;">提携カフェ</h2><div class="cafe-grid"><a href="/cafe.html" class="cafe-card" style="text-decoration:none;"><div class="card-img">珈琲・木漏れ日</div><div class="card-content"><h3 class="cafe-name">珈琲・木漏れ日</h3><p>大学裏の小さなカフェ。店主Kenさんの手淹れコーヒー。</p><div style="display:flex;gap:8px;margin-top:10px;"><span style="background:var(--light);padding:2px 8px;border-radius:4px;font-size:.8rem;">#英語OK</span><span style="background:var(--light);padding:2px 8px;border-radius:4px;font-size:.8rem;">#静か</span></div></div></a></div><a href="/" class="btn" style="display:block;text-align:center;">トップに戻る</a></div><footer style="text-align:center;padding:40px 0;font-size:.8rem;"><p>&copy; 2024 yurucafe</p></footer></body></html>`;

// ページ3: カフェ詳細（短縮版）
const cafeHTML = `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>珈琲・木漏れ日 | yurucafe</title><link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;500&family=Zen+Old+Mincho:wght@400;600&display=swap" rel="stylesheet"><style>:root{--bg:#F9F5F0;--text:#4A3B32;--accent:#A67B5B;--light:#E8Ddd4;--white:#fff;}*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'Zen Kaku Gothic New',sans-serif;background:var(--bg);color:var(--text);line-height:1.8;}.container{max-width:700px;margin:0 auto;padding:0 20px;}header{padding:20px 0;border-bottom:1px solid var(--light);}.nav-inner{display:flex;justify-content:space-between;align-items:center;}.logo{font-size:1.5rem;font-family:'Zen Old Mincho',serif;}.cafe-title{font-size:2rem;text-align:center;margin:40px 0 10px;}.owner{font-size:.9rem;color:#666;text-align:center;font-style:italic;margin-bottom:40px;}.video-placeholder{height:200px;background:#333;color:#fff;display:flex;align-items:center;justify-content:center;margin-bottom:40px;border-radius:8px;}.story{padding:30px;background:var(--white);border-radius:8px;margin-bottom:40px;border-left:4px solid var(--accent);}.btn{display:inline-block;background:var(--accent);color:var(--white);padding:15px 40px;border-radius:4px;font-size:1.1rem;margin:20px auto 0;display:block;text-align:center;max-width:300px;}</style></head><body><header><div class="container nav-inner"><a href="/" class="logo">yurucafe</a><nav><a href="/cafes.html">一覧へ戻る</a></nav></div></header><div class="container"><h1 class="cafe-title">珈琲・木漏れ日</h1><p class="owner">店主：Ken（ケンと呼んでください）</p><div class="video-placeholder">▶ Cafe Ambience (1:30)</div><div class="story"><h3 style="border-left:3px solid var(--accent);padding-left:15px;margin-bottom:20px;">「沈黙も会話の一部です」</h3><p>言葉が通じない国で過ごした経験から、この店を始めました。無理に話さなくてもいい。コーヒーの香りに包まれながら、あなたのペースで。</p><p>深煎りマンデリン。苦味の奥に甘みがあります。</p></div><div style="background:var(--white);padding:40px;text-align:center;border:1px solid var(--light);border-radius:8px;"><h3>対話を予約する</h3><p style="font-size:.9rem;margin-top:10px;">「yurucafeを見ました」と言えば学生割引あり</p><a href="/booking.html" class="btn">予約カレンダーを見る</a></div></div><footer style="text-align:center;padding:40px 0;font-size:.8rem;"><p>&copy; 2024 yurucafe</p></footer></body></html>`;

// ページ4: 予約（短縮版・JS付き）
const bookingHTML = `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>予約 | yurucafe</title><link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;500&family=Zen+Old+Mincho:wght@400;600&display=swap" rel="stylesheet"><style>:root{--bg:#F9F5F0;--text:#4A3B32;--accent:#A67B5B;--light:#E8Ddd4;--white:#fff;}*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'Zen Kaku Gothic New',sans-serif;background:var(--bg);color:var(--text);line-height:1.8;}.container{max-width:600px;margin:0 auto;padding:0 20px;}header{padding:20px 0;border-bottom:1px solid var(--light);}.nav-inner{display:flex;justify-content:space-between;align-items:center;}.logo{font-size:1.5rem;font-family:'Zen Old Mincho',serif;}.calendar{background:var(--white);padding:30px;border-radius:8px;border:1px solid var(--light);margin:40px 0;text-align:center;}.calendar-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:8px;margin-top:20px;}.day-name{font-size:.8rem;color:#888;font-weight:bold;}.date-btn{background:none;border:1px solid #ddd;padding:8px;cursor:pointer;border-radius:4px;font-size:.9rem;}.date-btn:hover{background:var(--light);}.date-btn.selected{background:var(--accent);color:var(--white);border-color:var(--accent);}.btn{background:var(--accent);color:var(--white);padding:15px 40px;border:none;border-radius:4px;font-size:1rem;cursor:pointer;margin-top:20px;opacity:.5;pointer-events:none;}.btn.active{opacity:1;pointer-events:auto;}.success-message{display:none;background:#E6F4EA;color:#1E4620;padding:20px;border-radius:8px;margin-top:20px;}</style></head><body><header><div class="container nav-inner"><a href="/" class="logo">yurucafe</a><nav><a href="/cafe.html">カフェ詳細へ</a></nav></div></header><div class="container"><div class="booking-header" style="text-align:center;margin-bottom:40px;"><h2>珈琲・木漏れ日 予約</h2><p style="font-size:.9rem;color:#666;">希望の日付を選択してください</p></div><div class="calendar"><div style="font-weight:bold;margin-bottom:15px;">今月</div><div class="calendar-grid" id="grid"><div class="day-name">日</div><div class="day-name">月</div><div class="day-name">火</div><div class="day-name">水</div><div class="day-name">木</div><div class="day-name">金</div><div class="day-name">土"></div></div><button id="book" class="btn">予約する</button><div id="success" class="success-message">予約リクエストを受け付けました。<br>店主Kenより、後ほどご連絡します。</div></div></div><script>const grid=document.getElementById('grid'),book=document.getElementById('book'),success=document.getElementById('success');for(let i=1;i<=14;i++){const btn=document.createElement('button');btn.className='date-btn';btn.textContent=i;btn.onclick=()=>{document.querySelectorAll('.date-btn').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');book.classList.add('active');book.onclick=()=> {book.style.display='none';success.style.display='block';};};grid.appendChild(btn);}</script></body></html>`;
